name: On pull request
on:
    pull_request:
      branches:
          - develop

jobs:
    Test-something:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Set up Python
              uses: actions/setup-python@v2
              
            - name: Set virtul env
              run: |
                python3 -m venv .venv
                source .venv/bin/activate

            - name: Istall requirements
              run: pip install -r requirements.txt
            
            - name: Testing app
              run: |
                python3 -m pytest --cov=test_app --cov-report=xml --cov-fail-under=70

            - name: Upload coverage report as artifact
              uses: actions/upload-artifact@v4.6.2
              with:
                name: coverage-report
                path: coverage.xml
    Build-project:
        runs-on: ubuntu-latest
        needs: Test-something
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Set up Python
              uses: actions/setup-python@v2

            - name: Istall requirements
              run: pip install -r requirements.txt              

            - name: Building 
              run: pyinstaller -F ./myapp/app.py

            - name: Update readme with status badge
              run: |
                  echo "[![On pull request](https://github.com/kaashntr/Git-Actions/actions/workflows/workflow.yml/badge.svg)](https://github.com/kaashntr/Git-Actions/actions/workflows/workflow.yml)" >> README.md
                  git config user.name "kaashntr"
                  git config user.email "kaashntr@github.com"
                  git add README.md
                  git commit -m "Update status badge in README"
                  git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kaashntr/Git-Actions.git main
                  git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kaashntr/Git-Actions.git HEAD:main
                  

            
              
            
                
