name: On push workflow
on:
    pull_request:
      branches:
          - develop

jobs:
    Test-something:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: Set up Python
              uses: actions/setup-python@v2
              
            - name: Set virtul env
              run: |
                python3 -m venv .venv
                source .venv/bin/activate

            - name: Istall requirements
              run: pip install -r requirements.txt
            
            - name: Testing app
              run: |
                python3 -m pytest --cov=test_app --cov-report=xml --cov-fail-under=70

            - name: Upload coverage report as artifact
              uses: actions/upload-artifact@v4.6.2
              with:
                name: coverage-report
                path: coverage.xml
                
                
